version: "3.7"

services:
  authorization_db:
    container_name: authorization-db
    image: postgres:11.2
    environment:
      POSTGRES_USER: meeteor13
      POSTGRES_PASSWORD: meeteor13
      POSTGRES_DB: meeteor13
    ports:
      - 5433:5432
    networks:
      - internal
    volumes:
      - authorization_db:/var/lib/postgresql

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:6.0.1
    depends_on:
      - authorization_db
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: authorization_db
      DB_PORT: 5432
      DB_DATABASE: meeteor13
      DB_SCHEMA: public
      DB_USER: meeteor13
      DB_PASSWORD: meeteor13
      KEYCLOAK_USER: solairerove
      KEYCLOAK_PASSWORD: 2033
    ports:
      - 8081:8080
    networks:
      - internal

volumes:
  authorization_db:

networks:
  internal:
    driver: bridge
