version: "3.7"

services:
  authorization-db:
    container_name: authorization-db
    image: postgres:11.2
    environment:
      POSTGRES_USER: meeteor13
      POSTGRES_PASSWORD: meeteor13
      POSTGRES_DB: meeteor13
    ports:
      - 5433:5432
    networks:
      - internal
    volumes:
      - ./devtools/init/postgres:/docker-entrypoint-initdb.d
      - authorization-db:/var/lib/postgresql

  authorization:
    container_name: authorization
    image: meeteor13/authorization:latest
    build: .
    depends_on:
      - authorization-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authorization-db:5432/meeteor13?user=meeteor13&password=meeteor13
    ports:
      - 8081:80
    networks:
      - internal

volumes:
  authorization-db:

networks:
  internal:
    driver: bridge
