server:
  port: 8080

spring:
  application:
    name: 'authorization'
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: true
  datasource:
    name: 'MeeteorPostgres'
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5433/meeteor13?user=meeteor13&password=meeteor13'

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    liquibase: WARN
