version: "3"

services:
  postgres:
    container_name: authorization-postgres
    image: postgres:9.5-alpine
    ports:
      - "5432:5432"
    networks:
      - meeteor13
    environment:
      - POSTGRES_USER=$PSUSER
      - POSTGRES_PASSWORD=$PSPASSWORD
      - POSTGRES_DB=$PSDB
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
      - platform-postgres-db:/var/lib/postgresql

volumes:
  platform-postgres-db:

networks:
  meeteor13:
    driver: bridge
